// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: protobuf/user.proto

package userpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Tokens
type TokensResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshUUID   string                 `protobuf:"bytes,1,opt,name=refreshUUID,proto3" json:"refreshUUID,omitempty"`
	AccessJWT     string                 `protobuf:"bytes,2,opt,name=accessJWT,proto3" json:"accessJWT,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokensResponse) Reset() {
	*x = TokensResponse{}
	mi := &file_protobuf_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokensResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokensResponse) ProtoMessage() {}

func (x *TokensResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokensResponse.ProtoReflect.Descriptor instead.
func (*TokensResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_user_proto_rawDescGZIP(), []int{0}
}

func (x *TokensResponse) GetRefreshUUID() string {
	if x != nil {
		return x.RefreshUUID
	}
	return ""
}

func (x *TokensResponse) GetAccessJWT() string {
	if x != nil {
		return x.AccessJWT
	}
	return ""
}

// Empty
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_protobuf_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_protobuf_user_proto_rawDescGZIP(), []int{1}
}

// GetProfile
type GetProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileRequest) Reset() {
	*x = GetProfileRequest{}
	mi := &file_protobuf_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileRequest) ProtoMessage() {}

func (x *GetProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileRequest.ProtoReflect.Descriptor instead.
func (*GetProfileRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_user_proto_rawDescGZIP(), []int{2}
}

func (x *GetProfileRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Date          string                 `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileResponse) Reset() {
	*x = GetProfileResponse{}
	mi := &file_protobuf_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileResponse) ProtoMessage() {}

func (x *GetProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileResponse.ProtoReflect.Descriptor instead.
func (*GetProfileResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_user_proto_rawDescGZIP(), []int{3}
}

func (x *GetProfileResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetProfileResponse) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

// SendOTPEmail
type SendOtpEmailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendOtpEmailRequest) Reset() {
	*x = SendOtpEmailRequest{}
	mi := &file_protobuf_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendOtpEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendOtpEmailRequest) ProtoMessage() {}

func (x *SendOtpEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendOtpEmailRequest.ProtoReflect.Descriptor instead.
func (*SendOtpEmailRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_user_proto_rawDescGZIP(), []int{4}
}

func (x *SendOtpEmailRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

type SendOtpEmailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendOtpEmailResponse) Reset() {
	*x = SendOtpEmailResponse{}
	mi := &file_protobuf_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendOtpEmailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendOtpEmailResponse) ProtoMessage() {}

func (x *SendOtpEmailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendOtpEmailResponse.ProtoReflect.Descriptor instead.
func (*SendOtpEmailResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_user_proto_rawDescGZIP(), []int{5}
}

func (x *SendOtpEmailResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

// VerifyOtp
type VerifyOtpRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Otp           string                 `protobuf:"bytes,2,opt,name=otp,proto3" json:"otp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyOtpRequest) Reset() {
	*x = VerifyOtpRequest{}
	mi := &file_protobuf_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyOtpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyOtpRequest) ProtoMessage() {}

func (x *VerifyOtpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyOtpRequest.ProtoReflect.Descriptor instead.
func (*VerifyOtpRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_user_proto_rawDescGZIP(), []int{6}
}

func (x *VerifyOtpRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *VerifyOtpRequest) GetOtp() string {
	if x != nil {
		return x.Otp
	}
	return ""
}

// RefreshTokens + Logout
type RefreshTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshUUID   string                 `protobuf:"bytes,1,opt,name=refreshUUID,proto3" json:"refreshUUID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenRequest) Reset() {
	*x = RefreshTokenRequest{}
	mi := &file_protobuf_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenRequest) ProtoMessage() {}

func (x *RefreshTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenRequest.ProtoReflect.Descriptor instead.
func (*RefreshTokenRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_user_proto_rawDescGZIP(), []int{7}
}

func (x *RefreshTokenRequest) GetRefreshUUID() string {
	if x != nil {
		return x.RefreshUUID
	}
	return ""
}

// ChangeUsername
type ChangeUsernameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	NewName       string                 `protobuf:"bytes,2,opt,name=newName,proto3" json:"newName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeUsernameRequest) Reset() {
	*x = ChangeUsernameRequest{}
	mi := &file_protobuf_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeUsernameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeUsernameRequest) ProtoMessage() {}

func (x *ChangeUsernameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeUsernameRequest.ProtoReflect.Descriptor instead.
func (*ChangeUsernameRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_user_proto_rawDescGZIP(), []int{8}
}

func (x *ChangeUsernameRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ChangeUsernameRequest) GetNewName() string {
	if x != nil {
		return x.NewName
	}
	return ""
}

var File_protobuf_user_proto protoreflect.FileDescriptor

const file_protobuf_user_proto_rawDesc = "" +
	"\n" +
	"\x13protobuf/user.proto\x12\x06userpb\"P\n" +
	"\x0eTokensResponse\x12 \n" +
	"\vrefreshUUID\x18\x01 \x01(\tR\vrefreshUUID\x12\x1c\n" +
	"\taccessJWT\x18\x02 \x01(\tR\taccessJWT\"\a\n" +
	"\x05Empty\"#\n" +
	"\x11GetProfileRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"<\n" +
	"\x12GetProfileResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04date\x18\x02 \x01(\tR\x04date\"+\n" +
	"\x13SendOtpEmailRequest\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\",\n" +
	"\x14SendOtpEmailResponse\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\":\n" +
	"\x10VerifyOtpRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x10\n" +
	"\x03otp\x18\x02 \x01(\tR\x03otp\"7\n" +
	"\x13RefreshTokenRequest\x12 \n" +
	"\vrefreshUUID\x18\x01 \x01(\tR\vrefreshUUID\"A\n" +
	"\x15ChangeUsernameRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\anewName\x18\x02 \x01(\tR\anewName2\xa4\x03\n" +
	"\vUserService\x12E\n" +
	"\n" +
	"GetProfile\x12\x19.userpb.GetProfileRequest\x1a\x1a.userpb.GetProfileResponse\"\x00\x12K\n" +
	"\fSendOtpEmail\x12\x1b.userpb.SendOtpEmailRequest\x1a\x1c.userpb.SendOtpEmailResponse\"\x00\x12?\n" +
	"\tVerifyOtp\x12\x18.userpb.VerifyOtpRequest\x1a\x16.userpb.TokensResponse\"\x00\x12F\n" +
	"\rRefreshTokens\x12\x1b.userpb.RefreshTokenRequest\x1a\x16.userpb.TokensResponse\"\x00\x126\n" +
	"\x06Logout\x12\x1b.userpb.RefreshTokenRequest\x1a\r.userpb.Empty\"\x00\x12@\n" +
	"\x0eChangeUsername\x12\x1d.userpb.ChangeUsernameRequest\x1a\r.userpb.Empty\"\x00B\n" +
	"Z\b./userpbb\x06proto3"

var (
	file_protobuf_user_proto_rawDescOnce sync.Once
	file_protobuf_user_proto_rawDescData []byte
)

func file_protobuf_user_proto_rawDescGZIP() []byte {
	file_protobuf_user_proto_rawDescOnce.Do(func() {
		file_protobuf_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protobuf_user_proto_rawDesc), len(file_protobuf_user_proto_rawDesc)))
	})
	return file_protobuf_user_proto_rawDescData
}

var file_protobuf_user_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_protobuf_user_proto_goTypes = []any{
	(*TokensResponse)(nil),        // 0: userpb.TokensResponse
	(*Empty)(nil),                 // 1: userpb.Empty
	(*GetProfileRequest)(nil),     // 2: userpb.GetProfileRequest
	(*GetProfileResponse)(nil),    // 3: userpb.GetProfileResponse
	(*SendOtpEmailRequest)(nil),   // 4: userpb.SendOtpEmailRequest
	(*SendOtpEmailResponse)(nil),  // 5: userpb.SendOtpEmailResponse
	(*VerifyOtpRequest)(nil),      // 6: userpb.VerifyOtpRequest
	(*RefreshTokenRequest)(nil),   // 7: userpb.RefreshTokenRequest
	(*ChangeUsernameRequest)(nil), // 8: userpb.ChangeUsernameRequest
}
var file_protobuf_user_proto_depIdxs = []int32{
	2, // 0: userpb.UserService.GetProfile:input_type -> userpb.GetProfileRequest
	4, // 1: userpb.UserService.SendOtpEmail:input_type -> userpb.SendOtpEmailRequest
	6, // 2: userpb.UserService.VerifyOtp:input_type -> userpb.VerifyOtpRequest
	7, // 3: userpb.UserService.RefreshTokens:input_type -> userpb.RefreshTokenRequest
	7, // 4: userpb.UserService.Logout:input_type -> userpb.RefreshTokenRequest
	8, // 5: userpb.UserService.ChangeUsername:input_type -> userpb.ChangeUsernameRequest
	3, // 6: userpb.UserService.GetProfile:output_type -> userpb.GetProfileResponse
	5, // 7: userpb.UserService.SendOtpEmail:output_type -> userpb.SendOtpEmailResponse
	0, // 8: userpb.UserService.VerifyOtp:output_type -> userpb.TokensResponse
	0, // 9: userpb.UserService.RefreshTokens:output_type -> userpb.TokensResponse
	1, // 10: userpb.UserService.Logout:output_type -> userpb.Empty
	1, // 11: userpb.UserService.ChangeUsername:output_type -> userpb.Empty
	6, // [6:12] is the sub-list for method output_type
	0, // [0:6] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protobuf_user_proto_init() }
func file_protobuf_user_proto_init() {
	if File_protobuf_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protobuf_user_proto_rawDesc), len(file_protobuf_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protobuf_user_proto_goTypes,
		DependencyIndexes: file_protobuf_user_proto_depIdxs,
		MessageInfos:      file_protobuf_user_proto_msgTypes,
	}.Build()
	File_protobuf_user_proto = out.File
	file_protobuf_user_proto_goTypes = nil
	file_protobuf_user_proto_depIdxs = nil
}
